# Generated by Django 4.2.11 on 2024-05-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0003_alter_farmerproduct_id_farmproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='id_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketingSystemApp.product'),
        ),
    ]
