# Generated by Django 4.2.11 on 2024-05-02 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0004_alter_farmerproduct_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
