# Generated by Django 4.2.11 on 2024-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0005_alter_product_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conveyance',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
