# Generated by Django 4.2.11 on 2024-05-02 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0006_customuser_age_customuser_conveyance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduct',
            name='id_product',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketingSystemApp.farmerproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='product_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='product_quality',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='product_volume',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='remaining_volume',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(default='Unité', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Nouveau Produit', max_length=255),
        ),
    ]
