# Generated by Django 4.2.11 on 2024-05-03 02:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0007_remove_farmerproduct_id_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_request',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='id_request',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(default='En attente', max_length=255),
        ),
    ]
