# Generated by Django 4.2.11 on 2024-05-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0008_alter_request_date_request_alter_request_id_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_approved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketingSystemApp.request'),
            preserve_default=False,
        ),
    ]
