# Generated by Django 4.2.11 on 2024-05-13 01:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0009_remove_transaction_id_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingoffer',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingSystemApp.request'),
        ),
        migrations.DeleteModel(
            name='Approved',
        ),
    ]
