# Generated by Django 4.2.11 on 2024-05-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0010_alter_financingoffer_id_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financingrequest',
            old_name='rating',
            new_name='content',
        ),
    ]
