# Generated by Django 4.2.11 on 2024-05-16 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0013_remove_recommandations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='farm_product',
        ),
        migrations.AddField(
            model_name='recommandation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingSystemApp.request'),
        ),
    ]
