# Generated by Django 4.2.11 on 2024-05-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0014_remove_recommandation_farm_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='id_request',
        ),
        migrations.AddField(
            model_name='recommandation',
            name='request',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='marketingSystemApp.financingrequest'),
            preserve_default=False,
        ),
    ]
