# Generated by Django 4.2.3 on 2024-05-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0015_remove_recommandation_id_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
