# Generated by Django 4.2.3 on 2024-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0016_alter_request_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product_volume',
            field=models.IntegerField(),
        ),
    ]
