# Generated by Django 4.2.3 on 2024-06-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0018_alter_request_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='certifications',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='production_method',
            field=models.CharField(choices=[('bio', 'Biologique'), ('hydroponie', 'Hydroponie'), ('durable', 'Durable')], default='conventionnel', max_length=50),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='quality',
            field=models.CharField(choices=[('bio', 'Bio'), ('conventionnel', 'Conventionnel'), ('premium', 'Premium')], default='conventionnel', max_length=50),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='season_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='season_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
