# Generated by Django 4.2.3 on 2024-07-09 02:40

from django.db import migrations, models

def set_default_asset(apps, schema_editor):
    FinancingOffer = apps.get_model('marketingSystemApp', 'FinancingOffer')
    for offer in FinancingOffer.objects.all():
        if offer.asset is None:
            offer.asset = 'Not specified'
            offer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0020_product_certifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='conveyance',
            new_name='asset',
        ),
        migrations.AddField(
            model_name='customuser',
            name='certification',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='children_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingoffer',
            name='age',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingoffer',
            name='asset',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingoffer',
            name='children_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingoffer',
            name='experience',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingoffer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_asset),
        migrations.AlterField(
            model_name='financingoffer',
            name='asset',
            field=models.CharField(max_length=255, default='Not specified'),
        ),
    ]
