# Generated by Django 4.2.3 on 2024-07-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0023_alter_financingoffer_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingoffer',
            name='asset',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
