# Generated by Django 4.2.3 on 2024-07-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0025_alter_financingoffer_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financingoffer',
            name='asset',
        ),
    ]
