# Generated by Django 4.2.3 on 2024-07-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0026_remove_financingoffer_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingoffer',
            name='asset',
            field=models.CharField(default='Not specified', max_length=255, null=True),
        ),
    ]
