# Generated by Django 4.2.3 on 2024-07-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0027_financingoffer_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
