# Generated by Django 4.2.3 on 2024-07-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingSystemApp', '0028_request_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id_request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='rating',
        ),
        migrations.AddField(
            model_name='request',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='need_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
